spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/child_job_db
    username: Malkollm
    password: f123456987
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect